### DISCUSSION TITLE
Is variable default value expansion is published and reliable

### DISCUSSION THREAD

**Discussion by ghost** [SCons/scons#4651] [Q&A] [answered]
Hello I've just thought about expansion and want to know if following code is reliable and deterministic.

```python
import SCons
from SCons.Variables import *

env = Environment()

options = Variables(["custom.py"], ARGUMENTS)

options.Add("my_option", "", "some_string")
options.Add("my_option2", "", "$my_option/${2+3}")

options.Update(env)

print(options.GenerateHelpText(env))
```

Following code prints as expected:

```
my_option: 
    default: some_string
    actual: test

my_option2: 
    default: $my_option/${2+3}
    actual: test/5
```

But inside docs I saw following https://scons.org/doc/production/HTML/scons-user.html#b-Substfile that `Substfile` can be nondeterministic in some cases. So are there similar limitations for this feature and is it published? I couldn't find it in the docs so... But looks like very intended beahavior so maybe it is published?
